exprTable: dedup breaks for DT
umccr/RNAsum pull request #96
Opened 2023-05-21 06:10 UTC by pdiakumis

Adding a fix to master for #93.
@skanwal could you test on your master setup whenever you get a chance?

Basically what's happening with the DT in exprTable is that we're getting 1801 quantiles for the expression values, those are then assigned colours, but there are lots of dups. Then you end up in a situation where you have 1,801 comparisons in Javascript like:

```
ifelse(x <= 10, 
       "blue1", 
       ifelse(x <= 10, 
              "blue2",
              ifelse(x <= 10, 
              "blue3", ...
```
... which becomes a bit of a mess to handle in particular for a Chrome browser.
Here I take the first ('head 1') of the colours assigned to each 'group' of breaks, so we end up with less breaks and colour values. Hopefully this works - it works on my machine!

2023-05-21 22:07 UTC, skanwal commented
Hi @pdiakumis - sure, I am testing it now.

2023-05-21 23:13 UTC, victorskl commented
![](https://github.trello.services/images/mini-trello-icon.png) [Portal Release - Snowshoe: RNAsum Chrome bug fix](https://trello.com/c/8C25jzLj/1458-portal-release-snowshoe-rnasum-chrome-bug-fix)

2023-05-22 03:03 UTC, skanwal requested changes
Thanks so much @pdiakumis.

I have made comments and quick fix in this PR. Hopefully, we can merge in this branch after you've reviewed https://github.com/umccr/RNAsum/pull/97. 

PS: works like a charm in chrome :)

2023-05-22 04:07 UTC, pdiakumis commented
Merging

2023-05-22 04:07 UTC, merged